export default class Exhibit {
    /**
     * @param {string} title - The medical condition or topic name.
     * @param {Array} models - Array of objects [{name, url, isZip}].
     * @param {string} story - The fairy tale mnemonic generated by Gemini.
     */
    constructor(title, models, story) {
        this.title = title;
        this.models = models;
        this.story = story;
        
        // Metadata for the frontend
        this.id = `exhibit-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
        this.createdAt = new Date().toISOString();
        
        // Suggested 3D Layout (Optional: can be used by Three.js to space items)
        this.layout = {
            spacing: 5,
            pedestals: [
                { x: -5, y: 0, z: 0 }, // Position for Prop 1
                { x: 0, y: 0, z: 0 },  // Position for Prop 2
                { x: 5, y: 0, z: 0 }   // Position for Prop 3
            ]
        };
    }

    /**
     * Validates if the exhibit has enough data to be rendered.
     */
    isValid() {
        return this.title && this.models.length > 0 && this.story;
    }

    /**
     * Returns a simplified version for logging or UI lists.
     */
    getSummary() {
        return {
            id: this.id,
            title: this.title,
            modelCount: this.models.length
        };
    }
}